import words from "an-array-of-english-words" with { type: "json" };
import { writeFileSync } from "node:fs";

const pinned = [
  "man", "woman", "boy", "girl", "help", "mother", "father", "student", "teacher",
  "doctor", "nurse", "phone", "medicine", "airport", "banana", "zebra", "music",
  "garden", "library", "school", "family", "friend", "home", "work", "money",
  "food", "water", "story", "letter", "window", "street", "morning", "night"
  , "computer", "internet", "screen", "keyboard", "mouse", "camera", "picture",
  "video", "book", "paper", "table", "chair", "car", "bus", "train", "bike",
  "city", "village", "country", "river", "mountain", "beach", "forest", "animal",
  "dog", "cat", "bird", "horse", "fish", "apple", "orange", "bread", "coffee",
  "tea", "house", "apartment", "room", "door", "floor", "ceiling", "wall",
  "shirt", "shoe", "coat", "bag", "box", "game", "movie", "song", "news",
  "idea", "plan", "goal", "job", "skill", "tool", "code", "data", "model",
  "search", "engine", "word", "sentence", "document", "result", "answer",
  "question", "person", "people", "child", "adult", "baby", "brother", "sister",
  "husband", "wife", "neighbor", "doctor", "lawyer", "artist", "writer", "chef",
  "police", "firefighter", "driver", "pilot", "farmer", "worker", "manager"
];

function hashWord(word) {
  let hash = 2166136261;
  for (let i = 0; i < word.length; i += 1) {
    hash ^= word.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

const filtered = [...new Set(words)]
  .filter((word) => /^[a-z]+$/.test(word))
  .filter((word) => word.length >= 3 && word.length <= 12)
  .filter((word) => !/(.)\1\1/.test(word))
  .filter((word) => !word.endsWith("ing") || word.length <= 9);

const sampled = filtered
  .sort((a, b) => hashWord(a) - hashWord(b))
  .slice(0, 60000);

const lexicon = [...new Set([...pinned, ...sampled])].sort();
const source = `// Generated by scripts/build-lexicon.mjs from an-array-of-english-words.\nexport const generalWords = ${JSON.stringify(lexicon)} as const;\n`;

writeFileSync(new URL("../src/lexicon.ts", import.meta.url), source);
console.log(`wrote ${lexicon.length} words to src/lexicon.ts`);
